@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Nov 04 20:38:42 +0800 2022
REM SW Build 3526262 on Mon Apr 18 15:48:16 MDT 2022
REM
REM IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim sym_det_tb_behav -key {Behavioral:sim_1:Functional:sym_det_tb} -tclbatch sym_det_tb.tcl -view D:/one drive for HKU/OneDrive - connect.hku.hk/HKU year 3 courses/sem1/ELEC3342/Assignment for this year/A2/part B/elec3342_hw2_src/symb_det/sym_det_tb_behav.wcfg -log simulate.log"
call xsim  sym_det_tb_behav -key {Behavioral:sim_1:Functional:sym_det_tb} -tclbatch sym_det_tb.tcl -view D:/one drive for HKU/OneDrive - connect.hku.hk/HKU year 3 courses/sem1/ELEC3342/Assignment for this year/A2/part B/elec3342_hw2_src/symb_det/sym_det_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
